[build]
builder = "nixpacks"

[build.nixpacks]
# Don't require secrets during build
aptPkgs = ["libatomic1"]

[deploy]
startCommand = "pnpm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
